namespace CallTracker.View
{
    partial class StatsView
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.nextTip = new System.Windows.Forms.Button();
            this._StatsPanel = new System.Windows.Forms.Panel();
            this._PCph = new CallTracker.View.LabelledTextBoxLong();
            this.bindingSource1 = new System.Windows.Forms.BindingSource(this.components);
            this._CurrCall = new CallTracker.View.LabelledTextBoxLong();
            this._CurrNotReady = new CallTracker.View.LabelledTextBoxLong();
            this.labelledHeading4 = new CallTracker.View.LabelledHeading();
            this._CurrHold = new CallTracker.View.LabelledTextBoxLong();
            this._CurrHandlingTime = new CallTracker.View.LabelledTextBoxLong();
            this._CurrWrapUp = new CallTracker.View.LabelledTextBoxLong();
            this._CurrTalkTime = new CallTracker.View.LabelledTextBoxLong();
            this._APHandlingTime = new CallTracker.View.LabelledTextBoxLong();
            this._APNotReady = new CallTracker.View.LabelledTextBoxLong();
            this._CNotReady = new CallTracker.View.LabelledTextBoxLong();
            this._CHeading = new CallTracker.View.LabelledHeading();
            this._ACHold = new CallTracker.View.LabelledTextBoxLong();
            this._CHold = new CallTracker.View.LabelledTextBoxLong();
            this._ACHandlingTime = new CallTracker.View.LabelledTextBoxLong();
            this._AReady = new CallTracker.View.LabelledTextBoxLong();
            this._ACNotReady = new CallTracker.View.LabelledTextBoxLong();
            this._ACWrapUp = new CallTracker.View.LabelledTextBoxLong();
            this._ACTalkTime = new CallTracker.View.LabelledTextBoxLong();
            this._AHeading = new CallTracker.View.LabelledHeading();
            this._PHeading = new CallTracker.View.LabelledHeading();
            this._CHandlingTime = new CallTracker.View.LabelledTextBoxLong();
            this._PReady = new CallTracker.View.LabelledTextBoxLong();
            this._PNotReady = new CallTracker.View.LabelledTextBoxLong();
            this._CWrapUp = new CallTracker.View.LabelledTextBoxLong();
            this._PCalls = new CallTracker.View.LabelledTextBoxLong();
            this._CTalkTime = new CallTracker.View.LabelledTextBoxLong();
            this._PLogin = new CallTracker.View.LabelledTextBoxLong();
            this._DateSelect = new CallTracker.View.LabelledComboBoxLong();
            this._Title = new System.Windows.Forms.Label();
            this._StatsPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).BeginInit();
            this.SuspendLayout();
            // 
            // nextTip
            // 
            this.nextTip.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.nextTip.BackColor = System.Drawing.Color.DarkSlateGray;
            this.nextTip.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.nextTip.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(198)))), ((int)(((byte)(0)))));
            this.nextTip.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.nextTip.Font = new System.Drawing.Font("Verdana", 7F);
            this.nextTip.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(198)))), ((int)(((byte)(0)))));
            this.nextTip.Location = new System.Drawing.Point(522, 218);
            this.nextTip.Margin = new System.Windows.Forms.Padding(0);
            this.nextTip.Name = "nextTip";
            this.nextTip.Size = new System.Drawing.Size(56, 22);
            this.nextTip.TabIndex = 36;
            this.nextTip.Text = "Done";
            this.nextTip.UseVisualStyleBackColor = false;
            this.nextTip.Click += new System.EventHandler(this.Cancel_Click);
            // 
            // _StatsPanel
            // 
            this._StatsPanel.BackColor = System.Drawing.Color.LightGray;
            this._StatsPanel.Controls.Add(this._PCph);
            this._StatsPanel.Controls.Add(this._CurrCall);
            this._StatsPanel.Controls.Add(this._CurrNotReady);
            this._StatsPanel.Controls.Add(this.labelledHeading4);
            this._StatsPanel.Controls.Add(this._CurrHold);
            this._StatsPanel.Controls.Add(this._CurrHandlingTime);
            this._StatsPanel.Controls.Add(this._CurrWrapUp);
            this._StatsPanel.Controls.Add(this._CurrTalkTime);
            this._StatsPanel.Controls.Add(this._APHandlingTime);
            this._StatsPanel.Controls.Add(this._APNotReady);
            this._StatsPanel.Controls.Add(this._CNotReady);
            this._StatsPanel.Controls.Add(this._CHeading);
            this._StatsPanel.Controls.Add(this._ACHold);
            this._StatsPanel.Controls.Add(this._CHold);
            this._StatsPanel.Controls.Add(this._ACHandlingTime);
            this._StatsPanel.Controls.Add(this._AReady);
            this._StatsPanel.Controls.Add(this._ACNotReady);
            this._StatsPanel.Controls.Add(this._ACWrapUp);
            this._StatsPanel.Controls.Add(this._ACTalkTime);
            this._StatsPanel.Controls.Add(this._AHeading);
            this._StatsPanel.Controls.Add(this._PHeading);
            this._StatsPanel.Controls.Add(this._CHandlingTime);
            this._StatsPanel.Controls.Add(this._PReady);
            this._StatsPanel.Controls.Add(this._PNotReady);
            this._StatsPanel.Controls.Add(this._CWrapUp);
            this._StatsPanel.Controls.Add(this._PCalls);
            this._StatsPanel.Controls.Add(this._CTalkTime);
            this._StatsPanel.Controls.Add(this._PLogin);
            this._StatsPanel.Location = new System.Drawing.Point(2, 4);
            this._StatsPanel.Name = "_StatsPanel";
            this._StatsPanel.Size = new System.Drawing.Size(580, 213);
            this._StatsPanel.TabIndex = 18;
            // 
            // _PCph
            // 
            this._PCph.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._PCph.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._PCph.BorderColour = System.Drawing.Color.White;
            this._PCph.ControlHeight = 20;
            this._PCph.Cursor = System.Windows.Forms.Cursors.Hand;
            this._PCph.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._PCph.DefaultText = "";
            this._PCph.Font = new System.Drawing.Font("Verdana", 7F);
            this._PCph.HasContextMenu = false;
            this._PCph.LabelActiveColor = System.Drawing.Color.Empty;
            this._PCph.LabelAutoSize = false;
            this._PCph.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._PCph.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this._PCph.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this._PCph.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._PCph.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._PCph.LabelInactiveColor = System.Drawing.Color.Empty;
            this._PCph.LabelMargin = new System.Windows.Forms.Padding(0);
            this._PCph.LabelOffset = new System.Drawing.Point(0, 0);
            this._PCph.LabelPadding = new System.Windows.Forms.Padding(0);
            this._PCph.LabelSize = new System.Drawing.Size(70, 20);
            this._PCph.LabelText = "cph";
            this._PCph.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._PCph.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._PCph.LabelToolTip = "";
            this._PCph.LabelVisible = true;
            this._PCph.Location = new System.Drawing.Point(3, 93);
            this._PCph.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._PCph.MenuButtonImage = null;
            this._PCph.Name = "_PCph";
            this._PCph.PropertyName = null;
            this._PCph.Size = new System.Drawing.Size(127, 20);
            this._PCph.TabIndex = 3;
            this._PCph.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._PCph.TextField = "";
            this._PCph.TextfieldToolTip = "Calls Per Hour: 3600/((AHT+NR)/Calls)";
            this._PCph.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._PCph.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._PCph.TFReadOnly = true;
            this._PCph.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._PCph.UseActiveLabel = false;
            // 
            // bindingSource1
            // 
            this.bindingSource1.DataSource = typeof(CallTracker.Model.DailyModel);
            // 
            // _CurrCall
            // 
            this._CurrCall.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CurrCall.BackColor = System.Drawing.Color.Goldenrod;
            this._CurrCall.BorderColour = System.Drawing.Color.Goldenrod;
            this._CurrCall.ControlHeight = 20;
            this._CurrCall.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CurrCall.DefaultText = "";
            this._CurrCall.Font = new System.Drawing.Font("Verdana", 7F);
            this._CurrCall.HasContextMenu = false;
            this._CurrCall.LabelActiveColor = System.Drawing.Color.Goldenrod;
            this._CurrCall.LabelAutoSize = false;
            this._CurrCall.LabelBorderColor = System.Drawing.Color.Goldenrod;
            this._CurrCall.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._CurrCall.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CurrCall.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._CurrCall.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CurrCall.LabelInactiveColor = System.Drawing.Color.Goldenrod;
            this._CurrCall.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CurrCall.LabelOffset = new System.Drawing.Point(0, 0);
            this._CurrCall.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CurrCall.LabelSize = new System.Drawing.Size(70, 20);
            this._CurrCall.LabelText = "call";
            this._CurrCall.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CurrCall.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CurrCall.LabelToolTip = "";
            this._CurrCall.LabelVisible = true;
            this._CurrCall.Location = new System.Drawing.Point(449, 188);
            this._CurrCall.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CurrCall.MenuButtonImage = null;
            this._CurrCall.Name = "_CurrCall";
            this._CurrCall.PropertyName = null;
            this._CurrCall.Size = new System.Drawing.Size(127, 20);
            this._CurrCall.TabIndex = 32;
            this._CurrCall.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CurrCall.TextField = "";
            this._CurrCall.TextfieldToolTip = "Current Call";
            this._CurrCall.TFBackColor = System.Drawing.SystemColors.Window;
            this._CurrCall.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CurrCall.TFReadOnly = true;
            this._CurrCall.TFTextColor = System.Drawing.SystemColors.ControlDarkDark;
            this._CurrCall.UseActiveLabel = false;
            // 
            // _CurrNotReady
            // 
            this._CurrNotReady.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CurrNotReady.BackColor = System.Drawing.Color.Goldenrod;
            this._CurrNotReady.BorderColour = System.Drawing.Color.Goldenrod;
            this._CurrNotReady.ControlHeight = 20;
            this._CurrNotReady.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CurrNotReady.DefaultText = "";
            this._CurrNotReady.Font = new System.Drawing.Font("Verdana", 7F);
            this._CurrNotReady.HasContextMenu = false;
            this._CurrNotReady.LabelActiveColor = System.Drawing.Color.Goldenrod;
            this._CurrNotReady.LabelAutoSize = false;
            this._CurrNotReady.LabelBorderColor = System.Drawing.Color.Goldenrod;
            this._CurrNotReady.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._CurrNotReady.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CurrNotReady.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._CurrNotReady.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CurrNotReady.LabelInactiveColor = System.Drawing.Color.Goldenrod;
            this._CurrNotReady.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CurrNotReady.LabelOffset = new System.Drawing.Point(0, 0);
            this._CurrNotReady.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CurrNotReady.LabelSize = new System.Drawing.Size(70, 20);
            this._CurrNotReady.LabelText = "not ready";
            this._CurrNotReady.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CurrNotReady.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CurrNotReady.LabelToolTip = "";
            this._CurrNotReady.LabelVisible = true;
            this._CurrNotReady.Location = new System.Drawing.Point(449, 69);
            this._CurrNotReady.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CurrNotReady.MenuButtonImage = null;
            this._CurrNotReady.Name = "_CurrNotReady";
            this._CurrNotReady.PropertyName = null;
            this._CurrNotReady.Size = new System.Drawing.Size(127, 20);
            this._CurrNotReady.TabIndex = 27;
            this._CurrNotReady.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CurrNotReady.TextField = "";
            this._CurrNotReady.TextfieldToolTip = "Current Not Ready";
            this._CurrNotReady.TFBackColor = System.Drawing.SystemColors.Window;
            this._CurrNotReady.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CurrNotReady.TFReadOnly = true;
            this._CurrNotReady.TFTextColor = System.Drawing.SystemColors.GrayText;
            this._CurrNotReady.UseActiveLabel = false;
            // 
            // labelledHeading4
            // 
            this.labelledHeading4.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.labelledHeading4.BackColor = System.Drawing.Color.Goldenrod;
            this.labelledHeading4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.labelledHeading4.ControlHeight = 20;
            this.labelledHeading4.Font = new System.Drawing.Font("Verdana", 7F);
            this.labelledHeading4.HasContextMenu = false;
            this.labelledHeading4.LabelActiveColor = System.Drawing.Color.Empty;
            this.labelledHeading4.LabelAutoSize = false;
            this.labelledHeading4.LabelBorderColor = System.Drawing.Color.Maroon;
            this.labelledHeading4.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this.labelledHeading4.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this.labelledHeading4.LabelDock = System.Windows.Forms.DockStyle.None;
            this.labelledHeading4.LabelFont = new System.Drawing.Font("Gautami", 7F);
            this.labelledHeading4.LabelInactiveColor = System.Drawing.Color.Empty;
            this.labelledHeading4.LabelMargin = new System.Windows.Forms.Padding(0);
            this.labelledHeading4.LabelOffset = new System.Drawing.Point(2, -3);
            this.labelledHeading4.LabelPadding = new System.Windows.Forms.Padding(0);
            this.labelledHeading4.LabelSize = new System.Drawing.Size(125, 22);
            this.labelledHeading4.LabelText = "CURRENT CALL";
            this.labelledHeading4.LabelTextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.labelledHeading4.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this.labelledHeading4.LabelToolTip = "";
            this.labelledHeading4.LabelVisible = true;
            this.labelledHeading4.Location = new System.Drawing.Point(449, 45);
            this.labelledHeading4.Margin = new System.Windows.Forms.Padding(0);
            this.labelledHeading4.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this.labelledHeading4.MenuButtonImage = null;
            this.labelledHeading4.Name = "labelledHeading4";
            this.labelledHeading4.PropertyName = null;
            this.labelledHeading4.Size = new System.Drawing.Size(127, 20);
            this.labelledHeading4.TabIndex = 104;
            // 
            // _CurrHold
            // 
            this._CurrHold.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CurrHold.BackColor = System.Drawing.Color.Goldenrod;
            this._CurrHold.BorderColour = System.Drawing.Color.Goldenrod;
            this._CurrHold.ControlHeight = 20;
            this._CurrHold.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CurrHold.DefaultText = "";
            this._CurrHold.Font = new System.Drawing.Font("Verdana", 7F);
            this._CurrHold.HasContextMenu = false;
            this._CurrHold.LabelActiveColor = System.Drawing.Color.Goldenrod;
            this._CurrHold.LabelAutoSize = false;
            this._CurrHold.LabelBorderColor = System.Drawing.Color.Goldenrod;
            this._CurrHold.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._CurrHold.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CurrHold.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._CurrHold.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CurrHold.LabelInactiveColor = System.Drawing.Color.Goldenrod;
            this._CurrHold.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CurrHold.LabelOffset = new System.Drawing.Point(0, 0);
            this._CurrHold.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CurrHold.LabelSize = new System.Drawing.Size(70, 20);
            this._CurrHold.LabelText = "hold";
            this._CurrHold.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CurrHold.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CurrHold.LabelToolTip = "";
            this._CurrHold.LabelVisible = true;
            this._CurrHold.Location = new System.Drawing.Point(449, 165);
            this._CurrHold.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CurrHold.MenuButtonImage = null;
            this._CurrHold.Name = "_CurrHold";
            this._CurrHold.PropertyName = null;
            this._CurrHold.Size = new System.Drawing.Size(127, 20);
            this._CurrHold.TabIndex = 31;
            this._CurrHold.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CurrHold.TextField = "";
            this._CurrHold.TextfieldToolTip = "Current Hold";
            this._CurrHold.TFBackColor = System.Drawing.SystemColors.Window;
            this._CurrHold.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CurrHold.TFReadOnly = true;
            this._CurrHold.TFTextColor = System.Drawing.SystemColors.GrayText;
            this._CurrHold.UseActiveLabel = false;
            // 
            // _CurrHandlingTime
            // 
            this._CurrHandlingTime.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CurrHandlingTime.BackColor = System.Drawing.Color.Goldenrod;
            this._CurrHandlingTime.BorderColour = System.Drawing.Color.Goldenrod;
            this._CurrHandlingTime.ControlHeight = 20;
            this._CurrHandlingTime.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CurrHandlingTime.DefaultText = "";
            this._CurrHandlingTime.Font = new System.Drawing.Font("Verdana", 7F);
            this._CurrHandlingTime.HasContextMenu = false;
            this._CurrHandlingTime.LabelActiveColor = System.Drawing.Color.Goldenrod;
            this._CurrHandlingTime.LabelAutoSize = false;
            this._CurrHandlingTime.LabelBorderColor = System.Drawing.Color.Goldenrod;
            this._CurrHandlingTime.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._CurrHandlingTime.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CurrHandlingTime.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._CurrHandlingTime.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CurrHandlingTime.LabelInactiveColor = System.Drawing.Color.Goldenrod;
            this._CurrHandlingTime.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CurrHandlingTime.LabelOffset = new System.Drawing.Point(0, 0);
            this._CurrHandlingTime.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CurrHandlingTime.LabelSize = new System.Drawing.Size(70, 20);
            this._CurrHandlingTime.LabelText = "handling time";
            this._CurrHandlingTime.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CurrHandlingTime.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CurrHandlingTime.LabelToolTip = "";
            this._CurrHandlingTime.LabelVisible = true;
            this._CurrHandlingTime.Location = new System.Drawing.Point(449, 93);
            this._CurrHandlingTime.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CurrHandlingTime.MenuButtonImage = null;
            this._CurrHandlingTime.Name = "_CurrHandlingTime";
            this._CurrHandlingTime.PropertyName = null;
            this._CurrHandlingTime.Size = new System.Drawing.Size(127, 20);
            this._CurrHandlingTime.TabIndex = 28;
            this._CurrHandlingTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CurrHandlingTime.TextField = "";
            this._CurrHandlingTime.TextfieldToolTip = "Call Talk + Wrap Up + Hold + Not Ready";
            this._CurrHandlingTime.TFBackColor = System.Drawing.SystemColors.Window;
            this._CurrHandlingTime.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CurrHandlingTime.TFReadOnly = true;
            this._CurrHandlingTime.TFTextColor = System.Drawing.SystemColors.GrayText;
            this._CurrHandlingTime.UseActiveLabel = false;
            // 
            // _CurrWrapUp
            // 
            this._CurrWrapUp.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CurrWrapUp.BackColor = System.Drawing.Color.Goldenrod;
            this._CurrWrapUp.BorderColour = System.Drawing.Color.Goldenrod;
            this._CurrWrapUp.ControlHeight = 20;
            this._CurrWrapUp.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CurrWrapUp.DefaultText = "";
            this._CurrWrapUp.Font = new System.Drawing.Font("Verdana", 7F);
            this._CurrWrapUp.HasContextMenu = false;
            this._CurrWrapUp.LabelActiveColor = System.Drawing.Color.Goldenrod;
            this._CurrWrapUp.LabelAutoSize = false;
            this._CurrWrapUp.LabelBorderColor = System.Drawing.Color.Goldenrod;
            this._CurrWrapUp.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._CurrWrapUp.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CurrWrapUp.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._CurrWrapUp.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CurrWrapUp.LabelInactiveColor = System.Drawing.Color.Goldenrod;
            this._CurrWrapUp.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CurrWrapUp.LabelOffset = new System.Drawing.Point(0, 0);
            this._CurrWrapUp.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CurrWrapUp.LabelSize = new System.Drawing.Size(70, 20);
            this._CurrWrapUp.LabelText = "wrap up";
            this._CurrWrapUp.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CurrWrapUp.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CurrWrapUp.LabelToolTip = "";
            this._CurrWrapUp.LabelVisible = true;
            this._CurrWrapUp.Location = new System.Drawing.Point(449, 141);
            this._CurrWrapUp.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CurrWrapUp.MenuButtonImage = null;
            this._CurrWrapUp.Name = "_CurrWrapUp";
            this._CurrWrapUp.PropertyName = null;
            this._CurrWrapUp.Size = new System.Drawing.Size(127, 20);
            this._CurrWrapUp.TabIndex = 30;
            this._CurrWrapUp.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CurrWrapUp.TextField = "";
            this._CurrWrapUp.TextfieldToolTip = "Current Wrap Up";
            this._CurrWrapUp.TFBackColor = System.Drawing.SystemColors.Window;
            this._CurrWrapUp.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CurrWrapUp.TFReadOnly = true;
            this._CurrWrapUp.TFTextColor = System.Drawing.SystemColors.GrayText;
            this._CurrWrapUp.UseActiveLabel = false;
            // 
            // _CurrTalkTime
            // 
            this._CurrTalkTime.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CurrTalkTime.BackColor = System.Drawing.Color.Goldenrod;
            this._CurrTalkTime.BorderColour = System.Drawing.Color.Goldenrod;
            this._CurrTalkTime.ControlHeight = 20;
            this._CurrTalkTime.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CurrTalkTime.DefaultText = "";
            this._CurrTalkTime.Font = new System.Drawing.Font("Verdana", 7F);
            this._CurrTalkTime.HasContextMenu = false;
            this._CurrTalkTime.LabelActiveColor = System.Drawing.Color.Goldenrod;
            this._CurrTalkTime.LabelAutoSize = false;
            this._CurrTalkTime.LabelBorderColor = System.Drawing.Color.Goldenrod;
            this._CurrTalkTime.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._CurrTalkTime.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CurrTalkTime.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._CurrTalkTime.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CurrTalkTime.LabelInactiveColor = System.Drawing.Color.Goldenrod;
            this._CurrTalkTime.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CurrTalkTime.LabelOffset = new System.Drawing.Point(0, 0);
            this._CurrTalkTime.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CurrTalkTime.LabelSize = new System.Drawing.Size(70, 20);
            this._CurrTalkTime.LabelText = "talk time";
            this._CurrTalkTime.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CurrTalkTime.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CurrTalkTime.LabelToolTip = "";
            this._CurrTalkTime.LabelVisible = true;
            this._CurrTalkTime.Location = new System.Drawing.Point(449, 117);
            this._CurrTalkTime.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CurrTalkTime.MenuButtonImage = null;
            this._CurrTalkTime.Name = "_CurrTalkTime";
            this._CurrTalkTime.PropertyName = null;
            this._CurrTalkTime.Size = new System.Drawing.Size(127, 20);
            this._CurrTalkTime.TabIndex = 29;
            this._CurrTalkTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CurrTalkTime.TextField = "";
            this._CurrTalkTime.TextfieldToolTip = "Current Talk Time";
            this._CurrTalkTime.TFBackColor = System.Drawing.SystemColors.Window;
            this._CurrTalkTime.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CurrTalkTime.TFReadOnly = true;
            this._CurrTalkTime.TFTextColor = System.Drawing.SystemColors.GrayText;
            this._CurrTalkTime.UseActiveLabel = false;
            // 
            // _APHandlingTime
            // 
            this._APHandlingTime.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._APHandlingTime.BackColor = System.Drawing.Color.DarkSlateGray;
            this._APHandlingTime.BorderColour = System.Drawing.Color.DarkSlateGray;
            this._APHandlingTime.ControlHeight = 20;
            this._APHandlingTime.Cursor = System.Windows.Forms.Cursors.Hand;
            this._APHandlingTime.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._APHandlingTime.DefaultText = "";
            this._APHandlingTime.Font = new System.Drawing.Font("Verdana", 7F);
            this._APHandlingTime.HasContextMenu = false;
            this._APHandlingTime.LabelActiveColor = System.Drawing.Color.Empty;
            this._APHandlingTime.LabelAutoSize = false;
            this._APHandlingTime.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._APHandlingTime.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._APHandlingTime.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._APHandlingTime.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._APHandlingTime.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._APHandlingTime.LabelInactiveColor = System.Drawing.Color.Empty;
            this._APHandlingTime.LabelMargin = new System.Windows.Forms.Padding(0);
            this._APHandlingTime.LabelOffset = new System.Drawing.Point(0, 0);
            this._APHandlingTime.LabelPadding = new System.Windows.Forms.Padding(0);
            this._APHandlingTime.LabelSize = new System.Drawing.Size(70, 20);
            this._APHandlingTime.LabelText = "not ready";
            this._APHandlingTime.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._APHandlingTime.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._APHandlingTime.LabelToolTip = "";
            this._APHandlingTime.LabelVisible = false;
            this._APHandlingTime.Location = new System.Drawing.Point(133, 93);
            this._APHandlingTime.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._APHandlingTime.MenuButtonImage = null;
            this._APHandlingTime.Name = "_APHandlingTime";
            this._APHandlingTime.PropertyName = null;
            this._APHandlingTime.Size = new System.Drawing.Size(57, 20);
            this._APHandlingTime.TabIndex = 10;
            this._APHandlingTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._APHandlingTime.TextField = "";
            this._APHandlingTime.TextfieldToolTip = "(Call Handling Time + Phone Not Ready)/Calls";
            this._APHandlingTime.TFBackColor = System.Drawing.SystemColors.Window;
            this._APHandlingTime.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._APHandlingTime.TFReadOnly = true;
            this._APHandlingTime.TFTextColor = System.Drawing.SystemColors.WindowText;
            this._APHandlingTime.UseActiveLabel = false;
            // 
            // _APNotReady
            // 
            this._APNotReady.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._APNotReady.BackColor = System.Drawing.Color.DarkSlateGray;
            this._APNotReady.BorderColour = System.Drawing.Color.DarkSlateGray;
            this._APNotReady.ControlHeight = 20;
            this._APNotReady.Cursor = System.Windows.Forms.Cursors.Hand;
            this._APNotReady.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._APNotReady.DefaultText = "";
            this._APNotReady.Font = new System.Drawing.Font("Verdana", 7F);
            this._APNotReady.HasContextMenu = false;
            this._APNotReady.LabelActiveColor = System.Drawing.Color.Empty;
            this._APNotReady.LabelAutoSize = false;
            this._APNotReady.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._APNotReady.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._APNotReady.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._APNotReady.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._APNotReady.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._APNotReady.LabelInactiveColor = System.Drawing.Color.Empty;
            this._APNotReady.LabelMargin = new System.Windows.Forms.Padding(0);
            this._APNotReady.LabelOffset = new System.Drawing.Point(0, 0);
            this._APNotReady.LabelPadding = new System.Windows.Forms.Padding(0);
            this._APNotReady.LabelSize = new System.Drawing.Size(70, 20);
            this._APNotReady.LabelText = "not ready";
            this._APNotReady.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._APNotReady.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._APNotReady.LabelToolTip = "";
            this._APNotReady.LabelVisible = false;
            this._APNotReady.Location = new System.Drawing.Point(133, 69);
            this._APNotReady.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._APNotReady.MenuButtonImage = null;
            this._APNotReady.Name = "_APNotReady";
            this._APNotReady.PropertyName = null;
            this._APNotReady.Size = new System.Drawing.Size(57, 20);
            this._APNotReady.TabIndex = 9;
            this._APNotReady.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._APNotReady.TextField = "";
            this._APNotReady.TextfieldToolTip = "(Call Not Ready + Phone Not Ready) / Calls";
            this._APNotReady.TFBackColor = System.Drawing.SystemColors.Window;
            this._APNotReady.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._APNotReady.TFReadOnly = true;
            this._APNotReady.TFTextColor = System.Drawing.SystemColors.WindowText;
            this._APNotReady.UseActiveLabel = false;
            // 
            // _CNotReady
            // 
            this._CNotReady.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CNotReady.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._CNotReady.BorderColour = System.Drawing.Color.White;
            this._CNotReady.ControlHeight = 20;
            this._CNotReady.Cursor = System.Windows.Forms.Cursors.Hand;
            this._CNotReady.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CNotReady.DefaultText = "";
            this._CNotReady.Font = new System.Drawing.Font("Verdana", 7F);
            this._CNotReady.HasContextMenu = false;
            this._CNotReady.LabelActiveColor = System.Drawing.Color.Empty;
            this._CNotReady.LabelAutoSize = false;
            this._CNotReady.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._CNotReady.LabelBorderOffset = new System.Drawing.Rectangle(-2, 0, 0, 0);
            this._CNotReady.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CNotReady.LabelDock = System.Windows.Forms.DockStyle.Right;
            this._CNotReady.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CNotReady.LabelInactiveColor = System.Drawing.Color.Empty;
            this._CNotReady.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CNotReady.LabelOffset = new System.Drawing.Point(57, 0);
            this._CNotReady.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CNotReady.LabelSize = new System.Drawing.Size(70, 20);
            this._CNotReady.LabelText = "not ready";
            this._CNotReady.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CNotReady.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CNotReady.LabelToolTip = "";
            this._CNotReady.LabelVisible = true;
            this._CNotReady.Location = new System.Drawing.Point(319, 69);
            this._CNotReady.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CNotReady.MenuButtonImage = null;
            this._CNotReady.Name = "_CNotReady";
            this._CNotReady.PropertyName = null;
            this._CNotReady.Size = new System.Drawing.Size(127, 20);
            this._CNotReady.TabIndex = 21;
            this._CNotReady.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CNotReady.TextField = "";
            this._CNotReady.TextfieldToolTip = "Total Call Not Ready";
            this._CNotReady.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._CNotReady.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CNotReady.TFReadOnly = true;
            this._CNotReady.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._CNotReady.UseActiveLabel = false;
            // 
            // _CHeading
            // 
            this._CHeading.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CHeading.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._CHeading.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this._CHeading.ControlHeight = 20;
            this._CHeading.Cursor = System.Windows.Forms.Cursors.Hand;
            this._CHeading.Font = new System.Drawing.Font("Verdana", 7F);
            this._CHeading.HasContextMenu = false;
            this._CHeading.LabelActiveColor = System.Drawing.Color.Empty;
            this._CHeading.LabelAutoSize = false;
            this._CHeading.LabelBorderColor = System.Drawing.Color.DarkGoldenrod;
            this._CHeading.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this._CHeading.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this._CHeading.LabelDock = System.Windows.Forms.DockStyle.None;
            this._CHeading.LabelFont = new System.Drawing.Font("Gautami", 7F);
            this._CHeading.LabelInactiveColor = System.Drawing.Color.Empty;
            this._CHeading.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CHeading.LabelOffset = new System.Drawing.Point(-3, -3);
            this._CHeading.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CHeading.LabelSize = new System.Drawing.Size(183, 23);
            this._CHeading.LabelText = "CALL TOTALS";
            this._CHeading.LabelTextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this._CHeading.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CHeading.LabelToolTip = "";
            this._CHeading.LabelVisible = true;
            this._CHeading.Location = new System.Drawing.Point(263, 45);
            this._CHeading.Margin = new System.Windows.Forms.Padding(0);
            this._CHeading.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CHeading.MenuButtonImage = null;
            this._CHeading.Name = "_CHeading";
            this._CHeading.PropertyName = null;
            this._CHeading.Size = new System.Drawing.Size(183, 20);
            this._CHeading.TabIndex = 103;
            // 
            // _ACHold
            // 
            this._ACHold.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._ACHold.BackColor = System.Drawing.Color.DarkSlateGray;
            this._ACHold.BorderColour = System.Drawing.Color.DarkSlateGray;
            this._ACHold.ControlHeight = 20;
            this._ACHold.Cursor = System.Windows.Forms.Cursors.Hand;
            this._ACHold.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._ACHold.DefaultText = "";
            this._ACHold.Font = new System.Drawing.Font("Verdana", 7F);
            this._ACHold.HasContextMenu = false;
            this._ACHold.LabelActiveColor = System.Drawing.Color.Empty;
            this._ACHold.LabelAutoSize = false;
            this._ACHold.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._ACHold.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._ACHold.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._ACHold.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._ACHold.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._ACHold.LabelInactiveColor = System.Drawing.Color.Empty;
            this._ACHold.LabelMargin = new System.Windows.Forms.Padding(0);
            this._ACHold.LabelOffset = new System.Drawing.Point(0, 0);
            this._ACHold.LabelPadding = new System.Windows.Forms.Padding(0);
            this._ACHold.LabelSize = new System.Drawing.Size(70, 20);
            this._ACHold.LabelText = "hold";
            this._ACHold.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._ACHold.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._ACHold.LabelToolTip = "";
            this._ACHold.LabelVisible = true;
            this._ACHold.Location = new System.Drawing.Point(189, 165);
            this._ACHold.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._ACHold.MenuButtonImage = null;
            this._ACHold.Name = "_ACHold";
            this._ACHold.PropertyName = null;
            this._ACHold.Size = new System.Drawing.Size(127, 20);
            this._ACHold.TabIndex = 19;
            this._ACHold.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._ACHold.TextField = "";
            this._ACHold.TextfieldToolTip = "Call Hold/Calls";
            this._ACHold.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(247)))));
            this._ACHold.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._ACHold.TFReadOnly = true;
            this._ACHold.TFTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(10)))), ((int)(((byte)(15)))));
            this._ACHold.UseActiveLabel = false;
            // 
            // _CHold
            // 
            this._CHold.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CHold.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._CHold.BorderColour = System.Drawing.Color.White;
            this._CHold.ControlHeight = 20;
            this._CHold.Cursor = System.Windows.Forms.Cursors.Hand;
            this._CHold.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CHold.DefaultText = "";
            this._CHold.Font = new System.Drawing.Font("Verdana", 7F);
            this._CHold.HasContextMenu = false;
            this._CHold.LabelActiveColor = System.Drawing.Color.Empty;
            this._CHold.LabelAutoSize = false;
            this._CHold.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._CHold.LabelBorderOffset = new System.Drawing.Rectangle(-2, 0, 0, 0);
            this._CHold.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CHold.LabelDock = System.Windows.Forms.DockStyle.Right;
            this._CHold.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CHold.LabelInactiveColor = System.Drawing.Color.Empty;
            this._CHold.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CHold.LabelOffset = new System.Drawing.Point(57, 0);
            this._CHold.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CHold.LabelSize = new System.Drawing.Size(70, 20);
            this._CHold.LabelText = "hold";
            this._CHold.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CHold.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CHold.LabelToolTip = "";
            this._CHold.LabelVisible = true;
            this._CHold.Location = new System.Drawing.Point(319, 165);
            this._CHold.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CHold.MenuButtonImage = null;
            this._CHold.Name = "_CHold";
            this._CHold.PropertyName = null;
            this._CHold.Size = new System.Drawing.Size(127, 20);
            this._CHold.TabIndex = 25;
            this._CHold.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CHold.TextField = "";
            this._CHold.TextfieldToolTip = "Total Hold";
            this._CHold.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._CHold.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CHold.TFReadOnly = true;
            this._CHold.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._CHold.UseActiveLabel = false;
            // 
            // _ACHandlingTime
            // 
            this._ACHandlingTime.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._ACHandlingTime.BackColor = System.Drawing.Color.DarkSlateGray;
            this._ACHandlingTime.BorderColour = System.Drawing.Color.DarkSlateGray;
            this._ACHandlingTime.ControlHeight = 20;
            this._ACHandlingTime.Cursor = System.Windows.Forms.Cursors.Hand;
            this._ACHandlingTime.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._ACHandlingTime.DefaultText = "";
            this._ACHandlingTime.Font = new System.Drawing.Font("Verdana", 7F);
            this._ACHandlingTime.HasContextMenu = false;
            this._ACHandlingTime.LabelActiveColor = System.Drawing.Color.Empty;
            this._ACHandlingTime.LabelAutoSize = false;
            this._ACHandlingTime.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._ACHandlingTime.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._ACHandlingTime.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._ACHandlingTime.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._ACHandlingTime.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._ACHandlingTime.LabelInactiveColor = System.Drawing.Color.Empty;
            this._ACHandlingTime.LabelMargin = new System.Windows.Forms.Padding(0);
            this._ACHandlingTime.LabelOffset = new System.Drawing.Point(0, 0);
            this._ACHandlingTime.LabelPadding = new System.Windows.Forms.Padding(0);
            this._ACHandlingTime.LabelSize = new System.Drawing.Size(70, 20);
            this._ACHandlingTime.LabelText = "aht";
            this._ACHandlingTime.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._ACHandlingTime.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._ACHandlingTime.LabelToolTip = "";
            this._ACHandlingTime.LabelVisible = true;
            this._ACHandlingTime.Location = new System.Drawing.Point(189, 93);
            this._ACHandlingTime.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._ACHandlingTime.MenuButtonImage = null;
            this._ACHandlingTime.Name = "_ACHandlingTime";
            this._ACHandlingTime.PropertyName = null;
            this._ACHandlingTime.Size = new System.Drawing.Size(127, 20);
            this._ACHandlingTime.TabIndex = 16;
            this._ACHandlingTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._ACHandlingTime.TextField = "";
            this._ACHandlingTime.TextfieldToolTip = "Call Handling Time/Calls";
            this._ACHandlingTime.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(247)))));
            this._ACHandlingTime.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._ACHandlingTime.TFReadOnly = true;
            this._ACHandlingTime.TFTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(10)))), ((int)(((byte)(15)))));
            this._ACHandlingTime.UseActiveLabel = false;
            // 
            // _AReady
            // 
            this._AReady.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._AReady.BackColor = System.Drawing.Color.DarkSlateGray;
            this._AReady.BorderColour = System.Drawing.Color.DarkSlateGray;
            this._AReady.ControlHeight = 20;
            this._AReady.Cursor = System.Windows.Forms.Cursors.Hand;
            this._AReady.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._AReady.DefaultText = "";
            this._AReady.Font = new System.Drawing.Font("Verdana", 7F);
            this._AReady.HasContextMenu = false;
            this._AReady.LabelActiveColor = System.Drawing.Color.DarkSlateGray;
            this._AReady.LabelAutoSize = false;
            this._AReady.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._AReady.LabelBorderOffset = new System.Drawing.Rectangle(-2, 0, 0, 0);
            this._AReady.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._AReady.LabelDock = System.Windows.Forms.DockStyle.Right;
            this._AReady.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._AReady.LabelInactiveColor = System.Drawing.Color.DarkSlateGray;
            this._AReady.LabelMargin = new System.Windows.Forms.Padding(0);
            this._AReady.LabelOffset = new System.Drawing.Point(57, 0);
            this._AReady.LabelPadding = new System.Windows.Forms.Padding(0);
            this._AReady.LabelSize = new System.Drawing.Size(70, 20);
            this._AReady.LabelText = "wait time";
            this._AReady.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._AReady.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._AReady.LabelToolTip = "";
            this._AReady.LabelVisible = true;
            this._AReady.Location = new System.Drawing.Point(133, 45);
            this._AReady.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._AReady.MenuButtonImage = null;
            this._AReady.Name = "_AReady";
            this._AReady.PropertyName = null;
            this._AReady.Size = new System.Drawing.Size(127, 20);
            this._AReady.TabIndex = 8;
            this._AReady.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._AReady.TextField = "";
            this._AReady.TextfieldToolTip = "Phone Ready/Calls";
            this._AReady.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(247)))));
            this._AReady.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._AReady.TFReadOnly = true;
            this._AReady.TFTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(10)))), ((int)(((byte)(15)))));
            this._AReady.UseActiveLabel = false;
            // 
            // _ACNotReady
            // 
            this._ACNotReady.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._ACNotReady.BackColor = System.Drawing.Color.DarkSlateGray;
            this._ACNotReady.BorderColour = System.Drawing.Color.DarkSlateGray;
            this._ACNotReady.ControlHeight = 20;
            this._ACNotReady.Cursor = System.Windows.Forms.Cursors.Hand;
            this._ACNotReady.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._ACNotReady.DefaultText = "";
            this._ACNotReady.Font = new System.Drawing.Font("Verdana", 7F);
            this._ACNotReady.HasContextMenu = false;
            this._ACNotReady.LabelActiveColor = System.Drawing.Color.Empty;
            this._ACNotReady.LabelAutoSize = false;
            this._ACNotReady.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._ACNotReady.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._ACNotReady.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._ACNotReady.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._ACNotReady.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._ACNotReady.LabelInactiveColor = System.Drawing.Color.Empty;
            this._ACNotReady.LabelMargin = new System.Windows.Forms.Padding(0);
            this._ACNotReady.LabelOffset = new System.Drawing.Point(0, 0);
            this._ACNotReady.LabelPadding = new System.Windows.Forms.Padding(0);
            this._ACNotReady.LabelSize = new System.Drawing.Size(70, 20);
            this._ACNotReady.LabelText = "not ready";
            this._ACNotReady.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._ACNotReady.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._ACNotReady.LabelToolTip = "";
            this._ACNotReady.LabelVisible = true;
            this._ACNotReady.Location = new System.Drawing.Point(189, 69);
            this._ACNotReady.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._ACNotReady.MenuButtonImage = null;
            this._ACNotReady.Name = "_ACNotReady";
            this._ACNotReady.PropertyName = null;
            this._ACNotReady.Size = new System.Drawing.Size(127, 20);
            this._ACNotReady.TabIndex = 15;
            this._ACNotReady.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._ACNotReady.TextField = "";
            this._ACNotReady.TextfieldToolTip = "Call Not Ready/ Calls";
            this._ACNotReady.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(247)))));
            this._ACNotReady.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._ACNotReady.TFReadOnly = true;
            this._ACNotReady.TFTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(10)))), ((int)(((byte)(15)))));
            this._ACNotReady.UseActiveLabel = false;
            // 
            // _ACWrapUp
            // 
            this._ACWrapUp.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._ACWrapUp.BackColor = System.Drawing.Color.DarkSlateGray;
            this._ACWrapUp.BorderColour = System.Drawing.Color.DarkSlateGray;
            this._ACWrapUp.ControlHeight = 20;
            this._ACWrapUp.Cursor = System.Windows.Forms.Cursors.Hand;
            this._ACWrapUp.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._ACWrapUp.DefaultText = "";
            this._ACWrapUp.Font = new System.Drawing.Font("Verdana", 7F);
            this._ACWrapUp.HasContextMenu = false;
            this._ACWrapUp.LabelActiveColor = System.Drawing.Color.Empty;
            this._ACWrapUp.LabelAutoSize = false;
            this._ACWrapUp.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._ACWrapUp.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._ACWrapUp.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._ACWrapUp.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._ACWrapUp.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._ACWrapUp.LabelInactiveColor = System.Drawing.Color.Empty;
            this._ACWrapUp.LabelMargin = new System.Windows.Forms.Padding(0);
            this._ACWrapUp.LabelOffset = new System.Drawing.Point(0, 0);
            this._ACWrapUp.LabelPadding = new System.Windows.Forms.Padding(0);
            this._ACWrapUp.LabelSize = new System.Drawing.Size(70, 20);
            this._ACWrapUp.LabelText = "wrap up";
            this._ACWrapUp.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._ACWrapUp.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._ACWrapUp.LabelToolTip = "";
            this._ACWrapUp.LabelVisible = true;
            this._ACWrapUp.Location = new System.Drawing.Point(189, 141);
            this._ACWrapUp.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._ACWrapUp.MenuButtonImage = null;
            this._ACWrapUp.Name = "_ACWrapUp";
            this._ACWrapUp.PropertyName = null;
            this._ACWrapUp.Size = new System.Drawing.Size(127, 20);
            this._ACWrapUp.TabIndex = 18;
            this._ACWrapUp.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._ACWrapUp.TextField = "";
            this._ACWrapUp.TextfieldToolTip = "Call Wrap Up/Calls";
            this._ACWrapUp.TFBackColor = System.Drawing.Color.White;
            this._ACWrapUp.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._ACWrapUp.TFReadOnly = true;
            this._ACWrapUp.TFTextColor = System.Drawing.SystemColors.ControlText;
            this._ACWrapUp.UseActiveLabel = false;
            // 
            // _ACTalkTime
            // 
            this._ACTalkTime.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._ACTalkTime.BackColor = System.Drawing.Color.DarkSlateGray;
            this._ACTalkTime.BorderColour = System.Drawing.Color.DarkSlateGray;
            this._ACTalkTime.ControlHeight = 20;
            this._ACTalkTime.Cursor = System.Windows.Forms.Cursors.Hand;
            this._ACTalkTime.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._ACTalkTime.DefaultText = "";
            this._ACTalkTime.Font = new System.Drawing.Font("Verdana", 7F);
            this._ACTalkTime.HasContextMenu = false;
            this._ACTalkTime.LabelActiveColor = System.Drawing.Color.Empty;
            this._ACTalkTime.LabelAutoSize = false;
            this._ACTalkTime.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._ACTalkTime.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._ACTalkTime.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._ACTalkTime.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._ACTalkTime.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._ACTalkTime.LabelInactiveColor = System.Drawing.Color.Empty;
            this._ACTalkTime.LabelMargin = new System.Windows.Forms.Padding(0);
            this._ACTalkTime.LabelOffset = new System.Drawing.Point(0, 0);
            this._ACTalkTime.LabelPadding = new System.Windows.Forms.Padding(0);
            this._ACTalkTime.LabelSize = new System.Drawing.Size(70, 20);
            this._ACTalkTime.LabelText = "talk time";
            this._ACTalkTime.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._ACTalkTime.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._ACTalkTime.LabelToolTip = "";
            this._ACTalkTime.LabelVisible = true;
            this._ACTalkTime.Location = new System.Drawing.Point(189, 117);
            this._ACTalkTime.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._ACTalkTime.MenuButtonImage = null;
            this._ACTalkTime.Name = "_ACTalkTime";
            this._ACTalkTime.PropertyName = null;
            this._ACTalkTime.Size = new System.Drawing.Size(127, 20);
            this._ACTalkTime.TabIndex = 17;
            this._ACTalkTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._ACTalkTime.TextField = "";
            this._ACTalkTime.TextfieldToolTip = "Call Talk Time/Calls";
            this._ACTalkTime.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(247)))));
            this._ACTalkTime.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._ACTalkTime.TFReadOnly = true;
            this._ACTalkTime.TFTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(10)))), ((int)(((byte)(15)))));
            this._ACTalkTime.UseActiveLabel = false;
            // 
            // _AHeading
            // 
            this._AHeading.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._AHeading.BackColor = System.Drawing.Color.DarkSlateGray;
            this._AHeading.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this._AHeading.ControlHeight = 20;
            this._AHeading.Cursor = System.Windows.Forms.Cursors.Hand;
            this._AHeading.Font = new System.Drawing.Font("Verdana", 7F);
            this._AHeading.HasContextMenu = false;
            this._AHeading.LabelActiveColor = System.Drawing.Color.Transparent;
            this._AHeading.LabelAutoSize = false;
            this._AHeading.LabelBorderColor = System.Drawing.Color.DarkSlateGray;
            this._AHeading.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this._AHeading.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this._AHeading.LabelDock = System.Windows.Forms.DockStyle.None;
            this._AHeading.LabelFont = new System.Drawing.Font("Gautami", 7F);
            this._AHeading.LabelInactiveColor = System.Drawing.Color.Transparent;
            this._AHeading.LabelMargin = new System.Windows.Forms.Padding(0);
            this._AHeading.LabelOffset = new System.Drawing.Point(2, -3);
            this._AHeading.LabelPadding = new System.Windows.Forms.Padding(0);
            this._AHeading.LabelSize = new System.Drawing.Size(180, 22);
            this._AHeading.LabelText = "AVERAGES";
            this._AHeading.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._AHeading.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._AHeading.LabelToolTip = "";
            this._AHeading.LabelVisible = true;
            this._AHeading.Location = new System.Drawing.Point(133, 22);
            this._AHeading.Margin = new System.Windows.Forms.Padding(0);
            this._AHeading.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._AHeading.MenuButtonImage = null;
            this._AHeading.Name = "_AHeading";
            this._AHeading.PropertyName = null;
            this._AHeading.Size = new System.Drawing.Size(183, 20);
            this._AHeading.TabIndex = 102;
            // 
            // _PHeading
            // 
            this._PHeading.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._PHeading.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._PHeading.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this._PHeading.ControlHeight = 15;
            this._PHeading.Cursor = System.Windows.Forms.Cursors.Hand;
            this._PHeading.Font = new System.Drawing.Font("Verdana", 7F);
            this._PHeading.HasContextMenu = false;
            this._PHeading.LabelActiveColor = System.Drawing.Color.DarkSlateGray;
            this._PHeading.LabelAutoSize = false;
            this._PHeading.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._PHeading.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this._PHeading.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this._PHeading.LabelDock = System.Windows.Forms.DockStyle.None;
            this._PHeading.LabelFont = new System.Drawing.Font("Gautami", 7F);
            this._PHeading.LabelInactiveColor = System.Drawing.Color.DarkSlateGray;
            this._PHeading.LabelMargin = new System.Windows.Forms.Padding(0);
            this._PHeading.LabelOffset = new System.Drawing.Point(4, -3);
            this._PHeading.LabelPadding = new System.Windows.Forms.Padding(0);
            this._PHeading.LabelSize = new System.Drawing.Size(187, 18);
            this._PHeading.LabelText = "PHONE TOTALS";
            this._PHeading.LabelTextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this._PHeading.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._PHeading.LabelToolTip = "";
            this._PHeading.LabelVisible = true;
            this._PHeading.Location = new System.Drawing.Point(3, 4);
            this._PHeading.Margin = new System.Windows.Forms.Padding(0);
            this._PHeading.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._PHeading.MenuButtonImage = null;
            this._PHeading.Name = "_PHeading";
            this._PHeading.PropertyName = null;
            this._PHeading.Size = new System.Drawing.Size(187, 15);
            this._PHeading.TabIndex = 101;
            // 
            // _CHandlingTime
            // 
            this._CHandlingTime.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CHandlingTime.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._CHandlingTime.BorderColour = System.Drawing.Color.White;
            this._CHandlingTime.ControlHeight = 20;
            this._CHandlingTime.Cursor = System.Windows.Forms.Cursors.Hand;
            this._CHandlingTime.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CHandlingTime.DefaultText = "";
            this._CHandlingTime.Font = new System.Drawing.Font("Verdana", 7F);
            this._CHandlingTime.HasContextMenu = false;
            this._CHandlingTime.LabelActiveColor = System.Drawing.Color.Empty;
            this._CHandlingTime.LabelAutoSize = false;
            this._CHandlingTime.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._CHandlingTime.LabelBorderOffset = new System.Drawing.Rectangle(-2, 0, 0, 0);
            this._CHandlingTime.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CHandlingTime.LabelDock = System.Windows.Forms.DockStyle.Right;
            this._CHandlingTime.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CHandlingTime.LabelInactiveColor = System.Drawing.Color.Empty;
            this._CHandlingTime.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CHandlingTime.LabelOffset = new System.Drawing.Point(57, 0);
            this._CHandlingTime.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CHandlingTime.LabelSize = new System.Drawing.Size(70, 20);
            this._CHandlingTime.LabelText = "handling time";
            this._CHandlingTime.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CHandlingTime.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CHandlingTime.LabelToolTip = "";
            this._CHandlingTime.LabelVisible = true;
            this._CHandlingTime.Location = new System.Drawing.Point(319, 93);
            this._CHandlingTime.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CHandlingTime.MenuButtonImage = null;
            this._CHandlingTime.Name = "_CHandlingTime";
            this._CHandlingTime.PropertyName = null;
            this._CHandlingTime.Size = new System.Drawing.Size(127, 20);
            this._CHandlingTime.TabIndex = 22;
            this._CHandlingTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CHandlingTime.TextField = "";
            this._CHandlingTime.TextfieldToolTip = "Total Call Handling Time";
            this._CHandlingTime.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._CHandlingTime.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CHandlingTime.TFReadOnly = true;
            this._CHandlingTime.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._CHandlingTime.UseActiveLabel = false;
            // 
            // _PReady
            // 
            this._PReady.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._PReady.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._PReady.BorderColour = System.Drawing.Color.White;
            this._PReady.ControlHeight = 20;
            this._PReady.Cursor = System.Windows.Forms.Cursors.Hand;
            this._PReady.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._PReady.DefaultText = "";
            this._PReady.Font = new System.Drawing.Font("Verdana", 7F);
            this._PReady.HasContextMenu = false;
            this._PReady.LabelActiveColor = System.Drawing.Color.Empty;
            this._PReady.LabelAutoSize = false;
            this._PReady.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._PReady.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this._PReady.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this._PReady.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._PReady.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._PReady.LabelInactiveColor = System.Drawing.Color.Empty;
            this._PReady.LabelMargin = new System.Windows.Forms.Padding(0);
            this._PReady.LabelOffset = new System.Drawing.Point(0, 0);
            this._PReady.LabelPadding = new System.Windows.Forms.Padding(0);
            this._PReady.LabelSize = new System.Drawing.Size(70, 20);
            this._PReady.LabelText = "ready";
            this._PReady.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._PReady.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._PReady.LabelToolTip = "";
            this._PReady.LabelVisible = true;
            this._PReady.Location = new System.Drawing.Point(3, 45);
            this._PReady.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._PReady.MenuButtonImage = null;
            this._PReady.Name = "_PReady";
            this._PReady.PropertyName = null;
            this._PReady.Size = new System.Drawing.Size(127, 20);
            this._PReady.TabIndex = 1;
            this._PReady.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._PReady.TextField = "";
            this._PReady.TextfieldToolTip = "Total Ready";
            this._PReady.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._PReady.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._PReady.TFReadOnly = true;
            this._PReady.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._PReady.UseActiveLabel = false;
            // 
            // _PNotReady
            // 
            this._PNotReady.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._PNotReady.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._PNotReady.BorderColour = System.Drawing.Color.White;
            this._PNotReady.ControlHeight = 20;
            this._PNotReady.Cursor = System.Windows.Forms.Cursors.Hand;
            this._PNotReady.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._PNotReady.DefaultText = "";
            this._PNotReady.Font = new System.Drawing.Font("Verdana", 7F);
            this._PNotReady.HasContextMenu = false;
            this._PNotReady.LabelActiveColor = System.Drawing.Color.Empty;
            this._PNotReady.LabelAutoSize = false;
            this._PNotReady.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._PNotReady.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this._PNotReady.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this._PNotReady.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._PNotReady.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._PNotReady.LabelInactiveColor = System.Drawing.Color.Empty;
            this._PNotReady.LabelMargin = new System.Windows.Forms.Padding(0);
            this._PNotReady.LabelOffset = new System.Drawing.Point(0, 0);
            this._PNotReady.LabelPadding = new System.Windows.Forms.Padding(0);
            this._PNotReady.LabelSize = new System.Drawing.Size(70, 20);
            this._PNotReady.LabelText = "not ready";
            this._PNotReady.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._PNotReady.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._PNotReady.LabelToolTip = "";
            this._PNotReady.LabelVisible = true;
            this._PNotReady.Location = new System.Drawing.Point(3, 69);
            this._PNotReady.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._PNotReady.MenuButtonImage = null;
            this._PNotReady.Name = "_PNotReady";
            this._PNotReady.PropertyName = null;
            this._PNotReady.Size = new System.Drawing.Size(127, 20);
            this._PNotReady.TabIndex = 2;
            this._PNotReady.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._PNotReady.TextField = "";
            this._PNotReady.TextfieldToolTip = "Total Phone Not Ready = First Ready - Login + Logout - Last Not Ready.";
            this._PNotReady.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._PNotReady.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._PNotReady.TFReadOnly = true;
            this._PNotReady.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._PNotReady.UseActiveLabel = false;
            // 
            // _CWrapUp
            // 
            this._CWrapUp.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CWrapUp.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._CWrapUp.BorderColour = System.Drawing.Color.White;
            this._CWrapUp.ControlHeight = 20;
            this._CWrapUp.Cursor = System.Windows.Forms.Cursors.Hand;
            this._CWrapUp.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CWrapUp.DefaultText = "";
            this._CWrapUp.Font = new System.Drawing.Font("Verdana", 7F);
            this._CWrapUp.HasContextMenu = false;
            this._CWrapUp.LabelActiveColor = System.Drawing.Color.Empty;
            this._CWrapUp.LabelAutoSize = false;
            this._CWrapUp.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._CWrapUp.LabelBorderOffset = new System.Drawing.Rectangle(-2, 0, 0, 0);
            this._CWrapUp.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CWrapUp.LabelDock = System.Windows.Forms.DockStyle.Right;
            this._CWrapUp.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CWrapUp.LabelInactiveColor = System.Drawing.Color.Empty;
            this._CWrapUp.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CWrapUp.LabelOffset = new System.Drawing.Point(57, 0);
            this._CWrapUp.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CWrapUp.LabelSize = new System.Drawing.Size(70, 20);
            this._CWrapUp.LabelText = "wrap up";
            this._CWrapUp.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CWrapUp.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CWrapUp.LabelToolTip = "";
            this._CWrapUp.LabelVisible = true;
            this._CWrapUp.Location = new System.Drawing.Point(319, 141);
            this._CWrapUp.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CWrapUp.MenuButtonImage = null;
            this._CWrapUp.Name = "_CWrapUp";
            this._CWrapUp.PropertyName = null;
            this._CWrapUp.Size = new System.Drawing.Size(127, 20);
            this._CWrapUp.TabIndex = 24;
            this._CWrapUp.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CWrapUp.TextField = "";
            this._CWrapUp.TextfieldToolTip = "Total Wrap Up";
            this._CWrapUp.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._CWrapUp.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CWrapUp.TFReadOnly = true;
            this._CWrapUp.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._CWrapUp.UseActiveLabel = false;
            // 
            // _PCalls
            // 
            this._PCalls.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._PCalls.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._PCalls.BorderColour = System.Drawing.Color.White;
            this._PCalls.ControlHeight = 20;
            this._PCalls.Cursor = System.Windows.Forms.Cursors.Hand;
            this._PCalls.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._PCalls.DefaultText = "";
            this._PCalls.Font = new System.Drawing.Font("Verdana", 7F);
            this._PCalls.HasContextMenu = false;
            this._PCalls.LabelActiveColor = System.Drawing.Color.Empty;
            this._PCalls.LabelAutoSize = false;
            this._PCalls.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._PCalls.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this._PCalls.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this._PCalls.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._PCalls.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._PCalls.LabelInactiveColor = System.Drawing.Color.Empty;
            this._PCalls.LabelMargin = new System.Windows.Forms.Padding(0);
            this._PCalls.LabelOffset = new System.Drawing.Point(0, 0);
            this._PCalls.LabelPadding = new System.Windows.Forms.Padding(0);
            this._PCalls.LabelSize = new System.Drawing.Size(70, 20);
            this._PCalls.LabelText = "calls";
            this._PCalls.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._PCalls.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._PCalls.LabelToolTip = "";
            this._PCalls.LabelVisible = true;
            this._PCalls.Location = new System.Drawing.Point(3, 188);
            this._PCalls.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._PCalls.MenuButtonImage = null;
            this._PCalls.Name = "_PCalls";
            this._PCalls.PropertyName = null;
            this._PCalls.Size = new System.Drawing.Size(127, 20);
            this._PCalls.TabIndex = 7;
            this._PCalls.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._PCalls.TextField = "";
            this._PCalls.TextfieldToolTip = "Number of Calls";
            this._PCalls.TFBackColor = System.Drawing.SystemColors.Window;
            this._PCalls.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._PCalls.TFReadOnly = true;
            this._PCalls.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._PCalls.UseActiveLabel = false;
            // 
            // _CTalkTime
            // 
            this._CTalkTime.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._CTalkTime.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._CTalkTime.BorderColour = System.Drawing.Color.White;
            this._CTalkTime.ControlHeight = 20;
            this._CTalkTime.Cursor = System.Windows.Forms.Cursors.Hand;
            this._CTalkTime.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._CTalkTime.DefaultText = "";
            this._CTalkTime.Font = new System.Drawing.Font("Verdana", 7F);
            this._CTalkTime.HasContextMenu = false;
            this._CTalkTime.LabelActiveColor = System.Drawing.Color.Empty;
            this._CTalkTime.LabelAutoSize = false;
            this._CTalkTime.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._CTalkTime.LabelBorderOffset = new System.Drawing.Rectangle(-2, 0, 0, 0);
            this._CTalkTime.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._CTalkTime.LabelDock = System.Windows.Forms.DockStyle.Right;
            this._CTalkTime.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._CTalkTime.LabelInactiveColor = System.Drawing.Color.Empty;
            this._CTalkTime.LabelMargin = new System.Windows.Forms.Padding(0);
            this._CTalkTime.LabelOffset = new System.Drawing.Point(57, 0);
            this._CTalkTime.LabelPadding = new System.Windows.Forms.Padding(0);
            this._CTalkTime.LabelSize = new System.Drawing.Size(70, 20);
            this._CTalkTime.LabelText = "talk time";
            this._CTalkTime.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._CTalkTime.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._CTalkTime.LabelToolTip = "";
            this._CTalkTime.LabelVisible = true;
            this._CTalkTime.Location = new System.Drawing.Point(319, 117);
            this._CTalkTime.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._CTalkTime.MenuButtonImage = null;
            this._CTalkTime.Name = "_CTalkTime";
            this._CTalkTime.PropertyName = null;
            this._CTalkTime.Size = new System.Drawing.Size(127, 20);
            this._CTalkTime.TabIndex = 23;
            this._CTalkTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._CTalkTime.TextField = "";
            this._CTalkTime.TextfieldToolTip = "Total Talk Time";
            this._CTalkTime.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._CTalkTime.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._CTalkTime.TFReadOnly = true;
            this._CTalkTime.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._CTalkTime.UseActiveLabel = false;
            // 
            // _PLogin
            // 
            this._PLogin.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._PLogin.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(173)))), ((int)(((byte)(179)))));
            this._PLogin.BorderColour = System.Drawing.Color.White;
            this._PLogin.ControlHeight = 20;
            this._PLogin.Cursor = System.Windows.Forms.Cursors.Hand;
            this._PLogin.DataBindings.Add(new System.Windows.Forms.Binding("TextField", this.bindingSource1, "Events", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._PLogin.DefaultText = "";
            this._PLogin.Font = new System.Drawing.Font("Verdana", 7F);
            this._PLogin.HasContextMenu = false;
            this._PLogin.LabelActiveColor = System.Drawing.Color.Empty;
            this._PLogin.LabelAutoSize = false;
            this._PLogin.LabelBorderColor = System.Drawing.Color.LightSeaGreen;
            this._PLogin.LabelBorderOffset = new System.Drawing.Rectangle(0, 0, 0, 0);
            this._PLogin.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.None;
            this._PLogin.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._PLogin.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._PLogin.LabelInactiveColor = System.Drawing.Color.Empty;
            this._PLogin.LabelMargin = new System.Windows.Forms.Padding(0);
            this._PLogin.LabelOffset = new System.Drawing.Point(0, 0);
            this._PLogin.LabelPadding = new System.Windows.Forms.Padding(0);
            this._PLogin.LabelSize = new System.Drawing.Size(70, 20);
            this._PLogin.LabelText = "login";
            this._PLogin.LabelTextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this._PLogin.LabelTextColor = System.Drawing.SystemColors.ControlLightLight;
            this._PLogin.LabelToolTip = "";
            this._PLogin.LabelVisible = true;
            this._PLogin.Location = new System.Drawing.Point(3, 22);
            this._PLogin.MenuButtonDock = System.Windows.Forms.DockStyle.Right;
            this._PLogin.MenuButtonImage = null;
            this._PLogin.Name = "_PLogin";
            this._PLogin.PropertyName = null;
            this._PLogin.Size = new System.Drawing.Size(127, 20);
            this._PLogin.TabIndex = 0;
            this._PLogin.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this._PLogin.TextField = "";
            this._PLogin.TextfieldToolTip = "Total Login";
            this._PLogin.TFBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(242)))));
            this._PLogin.TFCursor = System.Windows.Forms.Cursors.Arrow;
            this._PLogin.TFReadOnly = true;
            this._PLogin.TFTextColor = System.Drawing.Color.LightSlateGray;
            this._PLogin.UseActiveLabel = false;
            // 
            // _DateSelect
            // 
            this._DateSelect.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this._DateSelect.BackColor = System.Drawing.Color.DarkSlateGray;
            this._DateSelect.BorderColour = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(198)))), ((int)(((byte)(0)))));
            this._DateSelect.ControlHeight = 20;
            this._DateSelect.DataSource = null;
            this._DateSelect.DefaultText = "";
            this._DateSelect.Font = new System.Drawing.Font("Verdana", 7F);
            this._DateSelect.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(198)))), ((int)(((byte)(0)))));
            this._DateSelect.HasContextMenu = false;
            this._DateSelect.LabelActiveColor = System.Drawing.Color.Empty;
            this._DateSelect.LabelAutoSize = false;
            this._DateSelect.LabelBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(198)))), ((int)(((byte)(0)))));
            this._DateSelect.LabelBorderOffset = new System.Drawing.Rectangle(-1, 0, 1, 0);
            this._DateSelect.LabelBorderStyle = System.Windows.Forms.ButtonBorderStyle.Solid;
            this._DateSelect.LabelDock = System.Windows.Forms.DockStyle.Left;
            this._DateSelect.LabelFont = new System.Drawing.Font("Gautami", 8.25F);
            this._DateSelect.LabelInactiveColor = System.Drawing.Color.Empty;
            this._DateSelect.LabelMargin = new System.Windows.Forms.Padding(0);
            this._DateSelect.LabelOffset = new System.Drawing.Point(0, 0);
            this._DateSelect.LabelPadding = new System.Windows.Forms.Padding(0);
            this._DateSelect.LabelSize = new System.Drawing.Size(70, 20);
            this._DateSelect.LabelText = "date filter";
            this._DateSelect.LabelTextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this._DateSelect.LabelTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(198)))), ((int)(((byte)(0)))));
            this._DateSelect.LabelToolTip = "";
            this._DateSelect.LabelVisible = true;
            this._DateSelect.Location = new System.Drawing.Point(4, 219);
            this._DateSelect.MenuButtonDock = System.Windows.Forms.DockStyle.Left;
            this._DateSelect.MenuButtonImage = null;
            this._DateSelect.Name = "_DateSelect";
            this._DateSelect.OverlapLabel = false;
            this._DateSelect.PropertyName = "LongDate";
            this._DateSelect.Size = new System.Drawing.Size(127, 20);
            this._DateSelect.TabIndex = 35;
            // 
            // _Title
            // 
            this._Title.AutoSize = true;
            this._Title.BackColor = System.Drawing.Color.Transparent;
            this._Title.Font = new System.Drawing.Font("Optus Voice BETA Bold", 20F, System.Drawing.FontStyle.Bold);
            this._Title.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(198)))), ((int)(((byte)(0)))));
            this._Title.Location = new System.Drawing.Point(415, 213);
            this._Title.Name = "_Title";
            this._Title.Size = new System.Drawing.Size(112, 33);
            this._Title.TabIndex = 100;
            this._Title.Text = "//Stats";
            // 
            // StatsView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightSlateGray;
            this.Controls.Add(this.nextTip);
            this.Controls.Add(this._StatsPanel);
            this.Controls.Add(this._DateSelect);
            this.Controls.Add(this._Title);
            this.DoubleBuffered = true;
            this.Font = new System.Drawing.Font("Verdana", 7F);
            this.Name = "StatsView";
            this.Padding = new System.Windows.Forms.Padding(2, 3, 2, 2);
            this.Size = new System.Drawing.Size(584, 241);
            this._StatsPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label _Title;
        internal LabelledComboBoxLong _DateSelect;
        internal System.Windows.Forms.BindingSource bindingSource1;
        private System.Windows.Forms.Panel _StatsPanel;
        private LabelledTextBoxLong _PLogin;
        private LabelledTextBoxLong _CTalkTime;
        private LabelledTextBoxLong _CHandlingTime;
        private LabelledTextBoxLong _PReady;
        private LabelledTextBoxLong _PNotReady;
        private LabelledTextBoxLong _CWrapUp;
        private LabelledTextBoxLong _PCalls;
        private LabelledTextBoxLong _ACHandlingTime;
        private LabelledTextBoxLong _AReady;
        private LabelledTextBoxLong _ACNotReady;
        private LabelledTextBoxLong _ACWrapUp;
        private LabelledTextBoxLong _ACTalkTime;
        private LabelledHeading _AHeading;
        private LabelledHeading _PHeading;
        private LabelledTextBoxLong _ACHold;
        private LabelledTextBoxLong _CHold;
        private LabelledTextBoxLong _CNotReady;
        private LabelledHeading _CHeading;
        private LabelledTextBoxLong _APHandlingTime;
        private LabelledTextBoxLong _APNotReady;
        private LabelledTextBoxLong _CurrNotReady;
        private LabelledHeading labelledHeading4;
        private LabelledTextBoxLong _CurrHold;
        private LabelledTextBoxLong _CurrHandlingTime;
        private LabelledTextBoxLong _CurrWrapUp;
        private LabelledTextBoxLong _CurrTalkTime;
        private System.Windows.Forms.Button nextTip;
        private LabelledTextBoxLong _CurrCall;
        private LabelledTextBoxLong _PCph;
    }
}
